def gv
def version

pipeline{
    agent any
  tools {
    maven 'maven'
  }
    stages{
        stage("initialize_pipeline"){
        // here we are loading the groovy scripts
        // required = true
            steps{
                script{
                    gv = load "script.groovy"
                    echo "loaded script.groovy"
                }
            }
        }

        stage("increment version"){
        // increment version of pom.xml
            steps{
                script{
                    if (gv.isStringFoundInLastCommit("minor-update")){
                        gv.incrementMinorVersion()
                    } else if (gv.isStringFoundInLastCommit("major-update")){
                        gv.incrementMajorVersion()
                    } else {
                        gv.incrementPatchVersion()
                    }
                }
            }
        }
    }
}